# This is a basic workflow that is manually triggered
name: Test

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
    workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_commentary:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Webhook
      uses: distributhor/workflow-webhook
      with:
        url: "https://prod-21.centralus.logic.azure.com:443/workflows/1fbf0a3ec43243a9af04bd384bc86ce2/triggers/When_a_HTTP_request_is_received/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2FWhen_a_HTTP_request_is_received%2Frun&sv=1.0&sig=sA_uY0fsy-8AHTmdj0NqYlAmPttbM6al6tV4D7Pbdq4"
        json: '{"status":provisioned"", "id":"rando", "user":"Jason Cook", "userId":"f41d53ef-011e-4bba-8ecc-c77fd90b08d1", "messageId":"1728703287699", "msg":"output msg" }'